/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.ecommers.jooq.tables.references


import com.pl.sggw.ecommers.jooq.tables.Cart
import com.pl.sggw.ecommers.jooq.tables.CartProduct
import com.pl.sggw.ecommers.jooq.tables.Category
import com.pl.sggw.ecommers.jooq.tables.Customer
import com.pl.sggw.ecommers.jooq.tables.Product
import com.pl.sggw.ecommers.jooq.tables.StockPurchase



/**
 * The table <code>public.cart</code>.
 */
val CART = Cart.CART

/**
 * The table <code>public.cart_product</code>.
 */
val CART_PRODUCT = CartProduct.CART_PRODUCT

/**
 * The table <code>public.category</code>.
 */
val CATEGORY = Category.CATEGORY

/**
 * The table <code>public.customer</code>.
 */
val CUSTOMER = Customer.CUSTOMER

/**
 * The table <code>public.product</code>.
 */
val PRODUCT = Product.PRODUCT

/**
 * The table <code>public.stock_purchase</code>.
 */
val STOCK_PURCHASE = StockPurchase.STOCK_PURCHASE
