/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.ecommers.jooq.tables.records


import com.pl.sggw.ecommers.jooq.tables.Category

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CategoryRecord() : UpdatableRecordImpl<CategoryRecord>(Category.CATEGORY), Record5<Long?, String?, String?, LocalDateTime?, LocalDateTime?> {

    var id: Long?
        set(value) = set(0, value)
        get() = get(0) as Long?

    var name: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var treerepresentaion: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var creationTimestamp: LocalDateTime?
        set(value) = set(3, value)
        get() = get(3) as LocalDateTime?

    var modificationTimestamp: LocalDateTime?
        set(value) = set(4, value)
        get() = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<Long?, String?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row5<Long?, String?, String?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row5<Long?, String?, String?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row5<Long?, String?, String?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<Long?> = Category.CATEGORY.ID
    override fun field2(): Field<String?> = Category.CATEGORY.NAME
    override fun field3(): Field<String?> = Category.CATEGORY.TREEREPRESENTAION
    override fun field4(): Field<LocalDateTime?> = Category.CATEGORY.CREATION_TIMESTAMP
    override fun field5(): Field<LocalDateTime?> = Category.CATEGORY.MODIFICATION_TIMESTAMP
    override fun component1(): Long? = id
    override fun component2(): String? = name
    override fun component3(): String? = treerepresentaion
    override fun component4(): LocalDateTime? = creationTimestamp
    override fun component5(): LocalDateTime? = modificationTimestamp
    override fun value1(): Long? = id
    override fun value2(): String? = name
    override fun value3(): String? = treerepresentaion
    override fun value4(): LocalDateTime? = creationTimestamp
    override fun value5(): LocalDateTime? = modificationTimestamp

    override fun value1(value: Long?): CategoryRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): CategoryRecord {
        this.name = value
        return this
    }

    override fun value3(value: String?): CategoryRecord {
        this.treerepresentaion = value
        return this
    }

    override fun value4(value: LocalDateTime?): CategoryRecord {
        this.creationTimestamp = value
        return this
    }

    override fun value5(value: LocalDateTime?): CategoryRecord {
        this.modificationTimestamp = value
        return this
    }

    override fun values(value1: Long?, value2: String?, value3: String?, value4: LocalDateTime?, value5: LocalDateTime?): CategoryRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    constructor(id: Long? = null, name: String? = null, treerepresentaion: String? = null, creationTimestamp: LocalDateTime? = null, modificationTimestamp: LocalDateTime? = null): this() {
        this.id = id
        this.name = name
        this.treerepresentaion = treerepresentaion
        this.creationTimestamp = creationTimestamp
        this.modificationTimestamp = modificationTimestamp
    }
}
