/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.ecommers.jooq.tables


import com.pl.sggw.ecommers.jooq.Public
import com.pl.sggw.ecommers.jooq.keys.CART_PRODUCT_PKEY
import com.pl.sggw.ecommers.jooq.keys.CART_PRODUCT__CART_PRODUCT_CART_ID_FKEY
import com.pl.sggw.ecommers.jooq.keys.CART_PRODUCT__CART_PRODUCT_PRODUCT_ID_FKEY
import com.pl.sggw.ecommers.jooq.tables.records.CartProductRecord

import java.math.BigDecimal
import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CartProduct(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CartProductRecord>?,
    aliased: Table<CartProductRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CartProductRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.cart_product</code>
         */
        val CART_PRODUCT = CartProduct()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CartProductRecord> = CartProductRecord::class.java

    /**
     * The column <code>public.cart_product.id</code>.
     */
    val ID: TableField<CartProductRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.cart_product.cart_id</code>.
     */
    val CART_ID: TableField<CartProductRecord, Long?> = createField(DSL.name("cart_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.cart_product.product_id</code>.
     */
    val PRODUCT_ID: TableField<CartProductRecord, Long?> = createField(DSL.name("product_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.cart_product.quantity</code>.
     */
    val QUANTITY: TableField<CartProductRecord, BigDecimal?> = createField(DSL.name("quantity"), SQLDataType.NUMERIC, this, "")

    /**
     * The column <code>public.cart_product.price_per_item</code>.
     */
    val PRICE_PER_ITEM: TableField<CartProductRecord, BigDecimal?> = createField(DSL.name("price_per_item"), SQLDataType.NUMERIC(18, 2).nullable(false), this, "")

    /**
     * The column <code>public.cart_product.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<CartProductRecord, LocalDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CartProductRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CartProductRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.cart_product</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cart_product</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.cart_product</code> table reference
     */
    constructor(): this(DSL.name("cart_product"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CartProductRecord>): this(Internal.createPathAlias(child, key), child, key, CART_PRODUCT, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIdentity(): Identity<CartProductRecord, Long?> = super.getIdentity() as Identity<CartProductRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CartProductRecord> = CART_PRODUCT_PKEY
    override fun getKeys(): List<UniqueKey<CartProductRecord>> = listOf(CART_PRODUCT_PKEY)
    override fun getReferences(): List<ForeignKey<CartProductRecord, *>> = listOf(CART_PRODUCT__CART_PRODUCT_CART_ID_FKEY, CART_PRODUCT__CART_PRODUCT_PRODUCT_ID_FKEY)

    private lateinit var _cart: Cart
    private lateinit var _product: Product
    fun cart(): Cart {
        if (!this::_cart.isInitialized)
            _cart = Cart(this, CART_PRODUCT__CART_PRODUCT_CART_ID_FKEY)

        return _cart;
    }
    fun product(): Product {
        if (!this::_product.isInitialized)
            _product = Product(this, CART_PRODUCT__CART_PRODUCT_PRODUCT_ID_FKEY)

        return _product;
    }
    override fun `as`(alias: String): CartProduct = CartProduct(DSL.name(alias), this)
    override fun `as`(alias: Name): CartProduct = CartProduct(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CartProduct = CartProduct(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CartProduct = CartProduct(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Long?, Long?, Long?, BigDecimal?, BigDecimal?, LocalDateTime?> = super.fieldsRow() as Row6<Long?, Long?, Long?, BigDecimal?, BigDecimal?, LocalDateTime?>
}
