/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.ecommers.jooq.tables


import com.pl.sggw.ecommers.jooq.Public
import com.pl.sggw.ecommers.jooq.keys.CATEGORY_PKEY
import com.pl.sggw.ecommers.jooq.keys.CATEGORY_TREEREPRESENTAION_KEY
import com.pl.sggw.ecommers.jooq.tables.records.CategoryRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Category(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CategoryRecord>?,
    aliased: Table<CategoryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CategoryRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.category</code>
         */
        val CATEGORY = Category()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CategoryRecord> = CategoryRecord::class.java

    /**
     * The column <code>public.category.id</code>.
     */
    val ID: TableField<CategoryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.category.name</code>.
     */
    val NAME: TableField<CategoryRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(126).nullable(false), this, "")

    /**
     * The column <code>public.category.treerepresentaion</code>.
     */
    val TREEREPRESENTAION: TableField<CategoryRecord, String?> = createField(DSL.name("treerepresentaion"), SQLDataType.VARCHAR(12).nullable(false), this, "")

    /**
     * The column <code>public.category.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<CategoryRecord, LocalDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.category.modification_timestamp</code>.
     */
    val MODIFICATION_TIMESTAMP: TableField<CategoryRecord, LocalDateTime?> = createField(DSL.name("modification_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CategoryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CategoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.category</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.category</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.category</code> table reference
     */
    constructor(): this(DSL.name("category"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CategoryRecord>): this(Internal.createPathAlias(child, key), child, key, CATEGORY, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIdentity(): Identity<CategoryRecord, Long?> = super.getIdentity() as Identity<CategoryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CategoryRecord> = CATEGORY_PKEY
    override fun getKeys(): List<UniqueKey<CategoryRecord>> = listOf(CATEGORY_PKEY, CATEGORY_TREEREPRESENTAION_KEY)
    override fun `as`(alias: String): Category = Category(DSL.name(alias), this)
    override fun `as`(alias: Name): Category = Category(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Category = Category(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Category = Category(name, null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Long?, String?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row5<Long?, String?, String?, LocalDateTime?, LocalDateTime?>
}
