/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.ecommers.jooq.tables


import com.pl.sggw.ecommers.jooq.Public
import com.pl.sggw.ecommers.jooq.keys.CUSTOMER_PKEY
import com.pl.sggw.ecommers.jooq.keys.CUSTOMER_USER_EMAIL_KEY
import com.pl.sggw.ecommers.jooq.tables.records.CustomerRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Customer(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CustomerRecord>?,
    aliased: Table<CustomerRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CustomerRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.customer</code>
         */
        val CUSTOMER = Customer()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CustomerRecord> = CustomerRecord::class.java

    /**
     * The column <code>public.customer.id</code>.
     */
    val ID: TableField<CustomerRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.customer.user_email</code>.
     */
    val USER_EMAIL: TableField<CustomerRecord, String?> = createField(DSL.name("user_email"), SQLDataType.VARCHAR(126), this, "")

    /**
     * The column <code>public.customer.password</code>.
     */
    val PASSWORD: TableField<CustomerRecord, String?> = createField(DSL.name("password"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.customer.name</code>.
     */
    val NAME: TableField<CustomerRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(126), this, "")

    /**
     * The column <code>public.customer.city</code>.
     */
    val CITY: TableField<CustomerRecord, String?> = createField(DSL.name("city"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.customer.street</code>.
     */
    val STREET: TableField<CustomerRecord, String?> = createField(DSL.name("street"), SQLDataType.VARCHAR(126), this, "")

    /**
     * The column <code>public.customer.post_code</code>.
     */
    val POST_CODE: TableField<CustomerRecord, String?> = createField(DSL.name("post_code"), SQLDataType.VARCHAR(6), this, "")

    /**
     * The column <code>public.customer.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<CustomerRecord, LocalDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.customer.modification_timestamp</code>.
     */
    val MODIFICATION_TIMESTAMP: TableField<CustomerRecord, LocalDateTime?> = createField(DSL.name("modification_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CustomerRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CustomerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.customer</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.customer</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.customer</code> table reference
     */
    constructor(): this(DSL.name("customer"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CustomerRecord>): this(Internal.createPathAlias(child, key), child, key, CUSTOMER, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIdentity(): Identity<CustomerRecord, Long?> = super.getIdentity() as Identity<CustomerRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CustomerRecord> = CUSTOMER_PKEY
    override fun getKeys(): List<UniqueKey<CustomerRecord>> = listOf(CUSTOMER_PKEY, CUSTOMER_USER_EMAIL_KEY)
    override fun `as`(alias: String): Customer = Customer(DSL.name(alias), this)
    override fun `as`(alias: Name): Customer = Customer(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Customer = Customer(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Customer = Customer(name, null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<Long?, String?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row9<Long?, String?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?>
}
